In [1]:
import pandas as pd

In [2]:
df_passive = pd.read_csv("passive_data.csv")
print(df_passive.shape)

(30194, 95)

In [3]:
# group by user-agent column and compute the total number of _id for each user-agent in a dataframe called bots_df
bots_df = df_passive.groupby("user-agent")["_id"].count().reset_index()
bots_df.rename(columns={"_id": "count"}, inplace=True)
# sort the result by the count of _id in descending order
bots_df = bots_df.sort_values(by="count", ascending=False).reset_index()
# display full col width of the dataframe
pd.set_option("display.max_colwidth", None)
bots_df.head(50)

,index,user-agent,count
0,1396,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/91.0.4472.124,3120
1,2655,python-httpx/0.28.1,2143
2,1407,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Firefox/121.0,1504
3,2387,"Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1",1503
4,2034,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/120.0.0.0,1465
5,1386,Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0,1458
6,2638,l9explore/1.2.2,1021
7,1170,Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36,900
8,43,Go-http-client/1.1,646
9,2246,Mozilla/5.0 (compatible; CensysInspect/1.1; +https://about.censys.io/),641
10,2453,Mozilla/5.0 zgrab/0.x,459
11,1324,"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36",402
12,1251,"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",382
13,182,Mozilla/5.0,347
14,1872,Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.1.5) Gecko/20091102 Firefox/3.5.5 (.NET CLR 3.5.30729),307
15,49,"Hello from Palo Alto Networks, find out more about our scans in https://docs-cortex.paloaltonetworks.com/r/1/Cortex-Xpanse/Scanning-activity",301
16,1353,"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36 Edg/90.0.818.46",228
17,2640,libredtail-http,224
18,1298,"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36",223
19,1184,"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",221
20,1346,"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36",212
21,2237,Mozilla/5.0 (compatible; AhrefsBot/7.0; +http://ahrefs.com/robot/),205
22,2314,Mozilla/5.0 (compatible; SeznamBot/4.0; +https://o-seznam.cz/napoveda/vyhledavani/en/seznambot-crawler/),195
23,2441,"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.6312.86 Safari/537.36 BitSightBot/1.0",188
24,2668,visionheight.com/scan Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Chrome/126.0.0.0 Safari/537.36,184
25,1213,"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",183
26,1264,"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36",168
27,808,"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",160
28,2633,facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php),159
29,1235,"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",150
30,2446,"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; ClaudeBot/1.0; +claudebot@anthropic.com)",142
31,177,Mozilla/4.0 (compatible; MSIE 9.0; Windows NT 6.1),135
32,633,"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5 (Gort)",134
33,2261,Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html),131
34,2451,"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36",127
35,64,Microsoft URL Control - 6.00.8862,118
36,1417,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0,118
37,2,-,116
38,2658,python-requests/2.32.5,103
39,786,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36,103
40,1955,"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",101
41,2625,curl/7.64.1,95
42,884,"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Safari/605.1.15",92
43,2306,Mozilla/5.0 (compatible; Nmap Scripting Engine; https://nmap.org/book/nse.html),91
44,830,"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36; compatible; OAI-SearchBot/1.0; +https://openai.com/searchbot",85
45,2439,"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.6312.86 Safari/537.36",82
46,1426,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0,81
47,1214,"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0",79
48,1521,"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36",78
49,1391,"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36, Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",75

In [4]:
# select rows from df_passive where user-agent contains bot insensitve 
df_passive_bots = df_passive[df_passive["user-agent"].str.contains("bot", case=False, na=False)]
print(df_passive_bots.shape)
bots_df = df_passive_bots.groupby("user-agent")["_id"].count().reset_index()
bots_df.rename(columns={"_id": "count"}, inplace=True)
print(bots_df.shape)
# sort the result by the count of _id in descending order
bots_df = bots_df.sort_values(by="count", ascending=False).reset_index()
bots_df.to_csv("bots_user_agents.csv", index=False)
# display full col width of the dataframe
pd.set_option("display.max_colwidth", None)
bots_df.head(50)

(1851, 95)
(87, 2)

,index,user-agent,count
0,29,Mozilla/5.0 (compatible; AhrefsBot/7.0; +http://ahrefs.com/robot/),205
1,50,Mozilla/5.0 (compatible; SeznamBot/4.0; +https://o-seznam.cz/napoveda/vyhledavani/en/seznambot-crawler/),195
2,62,"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.6312.86 Safari/537.36 BitSightBot/1.0",188
3,67,"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; ClaudeBot/1.0; +claudebot@anthropic.com)",142
4,39,Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html),131
5,72,"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36",127
6,23,"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36; compatible; OAI-SearchBot/1.0; +https://openai.com/searchbot",85
7,24,"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36; compatible; OAI-SearchBot/1.3; robots.txt; +https://openai.com/searchbot",69
8,32,Mozilla/5.0 (compatible; Bingbot/2.0; +http://www.bing.com/bingbot.htm),64
9,38,Mozilla/5.0 (compatible; Googlebot/2.1),59
10,48,Mozilla/5.0 (compatible; SERankingBacklinksBot/1.0; +https://seranking.com/backlinks-crawler),45
11,49,Mozilla/5.0 (compatible; SemrushBot/7~bl; +http://www.semrush.com/bot.html),42
12,33,Mozilla/5.0 (compatible; CUCH.org Archive Bot; +https://cuch.org/about),40
13,28,Mozilla/5.0 (compatible) SemanticScholarBot (+https://www.semanticscholar.org/crawler),39
14,46,Mozilla/5.0 (compatible; MojeekBot/0.11; +https://www.mojeek.com/bot.html),35
15,42,Mozilla/5.0 (compatible; MJ12bot/v1.4.8; http://mj12bot.com/),33
16,41,Mozilla/5.0 (compatible; IbouBot/1.0; +bot@ibou.io; +https://ibou.io/iboubot.html),30
17,2,AtlasBot/1.0 (+https://atlas.local/bot),25
18,43,Mozilla/5.0 (compatible; MJ12bot/v2.0.4; http://mj12bot.com/),23
19,37,Mozilla/5.0 (compatible; DotBot/1.2; +https://opensiteexplorer.org/dotbot; help@moz.com),20
20,44,Mozilla/5.0 (compatible; MJ12bot/v2.0.5; http://mj12bot.com/),19
21,25,"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15 (Applebot/0.1; +http://www.apple.com/go/applebot)",17
22,31,Mozilla/5.0 (compatible; AwarioBot/1.0; +https://awario.com/bots.html),16
23,70,"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; SleepBot/1.0; +http://sleepbot.com/) Chrome/131.0.0.0 Safari/537.36",13
24,60,Mozilla/5.0 (compatible; intelx.io_bot +https://intelx.io),12
25,68,"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; GPTBot/1.3; +https://openai.com/gptbot)",12
26,9,FyndSearchEngine-Crawler (by fynd.bot; https://fynd.bot),11
27,64,"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Amazonbot/0.1; +https://developer.amazon.com/support/amazonbot) Chrome/119.0.6045.214 Safari/537.36",11
28,4,CCBot/2.0 (https://commoncrawl.org/faq/),10
29,27,Mozilla/5.0 (adaptive-bot),10
30,74,Pandalytics/2.0 (https://domainsbot.com/pandalytics/),8
31,11,Googlebot,8
32,20,"Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",7
33,61,Mozilla/5.0 (compatible; wpbot/1.4; +https://forms.gle/ajBaxygz9jSR8p8G9),5
34,16,"Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.7632.159 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",5
35,73,OpenTheBoxBot/1.0,5
36,36,"Mozilla/5.0 (compatible; DotBot/1.1; http://www.opensiteexplorer.org/dotbot, help@moz.com)",5
37,14,"Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.7559.132 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",4
38,40,Mozilla/5.0 (compatible; Googlebot/2.1; +https://www.google.com/bot.html),4
39,8,FindFiles.net/1.0 (compatible; +https://findfiles.net/bot),4
40,0,2ip bot/1.1 (+https://2ip.io),3
41,77,SuperBot/4.4.0.60 (Windows XP),3
42,18,"Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.7680.177 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",3
43,7,DuckDuckBot/1.1; (+http://duckduckgo.com/duckduckbot.html),3
44,26,"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 SlaylyBot/1.0",2
45,86,yacybot (freeworld/global; aarch64 Linux 6.1.54-10001-gd517e36a604d; java 25.0.2; Etc/en) https://yacy.net/bot.html,2
46,1,AgentDataBot/1.0 (+https://agentdata.run/bot),2
47,85,yacybot (/global; amd64 Linux 6.8.0-90-generic; java 21.0.9; Etc/en) https://yacy.net/bot.html,2
48,71,"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.0.0 Safari/537.36",2
49,65,"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Amzn-SearchBot/0.1) Chrome/119.0.6045.214 Safari/537.36",2

In [5]:
# group by siteKey column and compute the total number of _id for each siteKey in a dataframe called bots_df
bots_df = df_passive.groupby("siteKey")["_id"].count().reset_index()
bots_df.rename(columns={"_id": "count"}, inplace=True)
# sort the result by the count of _id in descending order
bots_df = bots_df.sort_values(by="count", ascending=False).reset_index()
# display full col width of the dataframe
pd.set_option("display.max_colwidth", None)
bots_df.head(50)

   index siteKey  count
0      0   site0  27204
1      2   site2   1361
2      1   site1   1255
3      3   site5    225
4      4   site7    149